# Generated by Django 5.2.8 on 2025-11-18 23:40

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataCollectionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('source', models.CharField(help_text='Data source name', max_length=50)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('PARTIAL', 'Partial Success')], max_length=10)),
                ('records_created', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('execution_time_ms', models.IntegerField(help_text='Execution time in milliseconds')),
            ],
            options={
                'verbose_name': 'Data Collection Log',
                'verbose_name_plural': 'Data Collection Logs',
                'db_table': 'data_collection_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='MacroeconomicIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, help_text='Date of indicator', unique=True)),
                ('official_exchange_rate', models.DecimalField(blank=True, decimal_places=4, help_text='Official BOB/USD exchange rate', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('6.00'))])),
                ('monthly_inflation_rate', models.DecimalField(blank=True, decimal_places=4, help_text='Monthly inflation rate as percentage', max_digits=6, null=True)),
                ('accumulated_inflation', models.DecimalField(blank=True, decimal_places=4, help_text='Accumulated inflation for the year', max_digits=8, null=True)),
                ('source', models.CharField(choices=[('INE', 'Instituto Nacional de Estadística'), ('BCB', 'Banco Central de Bolivia'), ('OTHER', 'Other Source')], default='BCB', max_length=10)),
                ('raw_data', models.JSONField(blank=True, help_text='Raw data from source', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Macroeconomic Indicator',
                'verbose_name_plural': 'Macroeconomic Indicators',
                'db_table': 'macroeconomic_indicators',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date', 'source'], name='macroeconom_date_a5d6be_idx'), models.Index(fields=['-date'], name='macroeconom_date_ceb943_idx')],
            },
        ),
        migrations.CreateModel(
            name='MarketSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, help_text='Time when snapshot was captured')),
                ('average_sell_price', models.DecimalField(decimal_places=4, help_text='Average USDT sell price in BOB', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('6.00')), django.core.validators.MaxValueValidator(Decimal('8.00'))])),
                ('average_buy_price', models.DecimalField(blank=True, decimal_places=4, help_text='Average USDT buy price in BOB', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('6.00')), django.core.validators.MaxValueValidator(Decimal('8.00'))])),
                ('total_volume', models.DecimalField(decimal_places=2, help_text='Total USDT volume available', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('spread_percentage', models.DecimalField(blank=True, decimal_places=4, help_text='Price spread as percentage', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('num_active_traders', models.IntegerField(default=0, help_text='Number of active traders in snapshot', validators=[django.core.validators.MinValueValidator(0)])),
                ('data_quality_score', models.FloatField(default=1.0, help_text='Data quality score (0-1)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('raw_response', models.JSONField(blank=True, help_text='Raw API response for audit', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Market Snapshot',
                'verbose_name_plural': 'Market Snapshots',
                'db_table': 'market_snapshots',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp', 'average_sell_price'], name='market_snap_timesta_ce2fa1_idx'), models.Index(fields=['-timestamp'], name='market_snap_timesta_f7d646_idx'), models.Index(fields=['created_at'], name='market_snap_created_ed656b_idx')],
            },
        ),
    ]
