# Generated by Django 5.2.8 on 2025-11-29 06:13

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("market_data", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="marketsnapshot",
            name="average_buy_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Average USDT buy price in BOB",
                max_digits=8,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("5.00")),
                    django.core.validators.MaxValueValidator(Decimal("15.00")),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="marketsnapshot",
            name="average_sell_price",
            field=models.DecimalField(
                decimal_places=4,
                help_text="Average USDT sell price in BOB",
                max_digits=8,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("5.00")),
                    django.core.validators.MaxValueValidator(Decimal("15.00")),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="marketsnapshot",
            name="total_volume",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Total USDT volume available. Null for OHLC sources that don't provide volume.",
                max_digits=12,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
    ]
