# Generated by Django 5.2.8 on 2025-11-29 06:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("market_data", "0002_allow_null_volume"),
    ]

    operations = [
        migrations.AlterField(
            model_name="marketsnapshot",
            name="spread_percentage",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Price spread as percentage. Can be negative if sell_price < buy_price.",
                max_digits=6,
                null=True,
            ),
        ),
    ]
