# Generated by Django 5.2.8 on 2025-11-18 23:40

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ElasticityCalculation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_ip', models.GenericIPAddressField(blank=True, help_text='Client IP for rate limiting analytics (not auth)', null=True)),
                ('method', models.CharField(choices=[('MIDPOINT', 'Midpoint (Arc) Method'), ('REGRESSION', 'Log-Log Regression')], default='MIDPOINT', max_length=20)),
                ('start_date', models.DateTimeField(help_text='Start of analysis period')),
                ('end_date', models.DateTimeField(help_text='End of analysis period')),
                ('window_size', models.CharField(choices=[('HOURLY', 'Hourly'), ('DAILY', 'Daily'), ('WEEKLY', 'Weekly')], default='DAILY', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20)),
                ('elasticity_coefficient', models.DecimalField(blank=True, decimal_places=4, help_text='Calculated elasticity coefficient', max_digits=10, null=True)),
                ('classification', models.CharField(blank=True, choices=[('ELASTIC', 'Elastic Demand'), ('INELASTIC', 'Inelastic Demand'), ('UNITARY', 'Unitary Elastic')], max_length=20, null=True)),
                ('confidence_interval_lower', models.DecimalField(blank=True, decimal_places=4, help_text='95% confidence interval lower bound', max_digits=10, null=True)),
                ('confidence_interval_upper', models.DecimalField(blank=True, decimal_places=4, help_text='95% confidence interval upper bound', max_digits=10, null=True)),
                ('r_squared', models.DecimalField(blank=True, decimal_places=4, help_text='R² for regression method', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('standard_error', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('data_points_used', models.IntegerField(default=0, help_text='Number of observations used')),
                ('average_data_quality', models.FloatField(default=1.0, help_text='Average quality score of data points', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('error_message', models.TextField(blank=True, null=True)),
                ('calculation_metadata', models.JSONField(blank=True, default=dict, help_text='Additional calculation details')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Elasticity Calculation',
                'verbose_name_plural': 'Elasticity Calculations',
                'db_table': 'elasticity_calculations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='elasticity__created_2e803d_idx'), models.Index(fields=['status', '-created_at'], name='elasticity__status_0028ae_idx'), models.Index(fields=['client_ip', '-created_at'], name='elasticity__client__94189f_idx')],
            },
        ),
    ]
