# Generated by Django 5.2.8 on 2025-11-30 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elasticity", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="elasticitycalculation",
            name="is_reliable",
            field=models.BooleanField(
                default=True,
                help_text="Whether the elasticity coefficient is trustworthy",
            ),
        ),
        migrations.AddField(
            model_name="elasticitycalculation",
            name="reliability_note",
            field=models.TextField(
                blank=True,
                help_text="Explanation if result is flagged as unreliable",
                null=True,
            ),
        ),
    ]
